// Generated by SeaSite
// @jsx jsx

import { jsx, parseMarkdown, SeaSite } from 'seasite'

function generateSite() {

  let site = new SeaSite(
    'public',
    'dist', {
      includePatterns: [
        /^(\.htaccess|[^.].*)$/,
      ],
      excludePatterns: [],
      // baseURL: WEBSITE_PUBLIC_URL,
    })

  site.handle(/.*\.md/, (content, path) => {
    let $ = site.readDOM('template.html')
    let htmlPath = path.replace(/\.md$/, '.html')
    let md = parseMarkdown(content)
    let title = md.props.title
    $('title').text(`${title} - My Website`)
    $('#title').text(title)
    $('#content').html(md.html)
    site.write(htmlPath, $.html())
  })

}

generateSite()
